blogapp/urls.py
from django.urls import path
from .views import blog_detail, blog_list


urlpatterns = [
    path('', blog_list, name="blog_list"),
    path('<slug:slug>/', blog_detail, name='blog_detail'),
]

menuapp/urls.py
from django.urls import path
from .views import menu_list, menu_detail, menu_category

urlpatterns = [
    path('', menu_list, name="menu_list"),
    path('<slug:slug>/', menu_detail, name='menu_detail'),
    path('categoria/<slug:slug>/', menu_category, name='menu_category'),
]

murtaoweb/urls.py
from django.contrib import admin
from django.urls import path
from murtaoweb import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include(('blogapp.urls', 'blogapp'), namespace='blogapp')),
    path('eventos/', include(('eventosapp.urls', 'eventosapp'), namespace='eventosapp')),
    path('menu/', include(('menuapp.urls', 'menuapp'), namespace='menuapp')),
    path('contacto/', include(('contacto.urls', 'contacto'), namespace='contacto')),
    path('carta/', include(('cartaapp.urls', 'carta'), namespace='carta')),

    path('control/', include(('control_panelapp.urls', 'control_panelapp'), namespace='control_panelapp')),
    path('reservas/', include(('reservasapp.urls', 'reservasapp'), namespace='reservasapp')),
    path('suscripcion/', include(('suscripcionapp.urls', 'suscripcionapp'), namespace='suscripcionapp')),
    path('enviando/', TemplateView.as_view(template_name="reservasapp/contacto_enviando.html")),
    path('redirect/', TemplateView.as_view(template_name="reservasapp/reserva_redirect.html"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    ESTADO = (
        ('Borrador', 'Borrador'),
        ('Publicado', 'Publicado')
    )
    estado = models.CharField(max_length=12, choices=ESTADO, default='Borrador')
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    imagen_blog = models.ImageField()
    titulo = models.CharField(max_length=255)
    contenido = models.TextField()
    fecha_blog = models.DateField(default=timezone.now)
    hora_blog = models.TimeField(default=timezone.now)
    linkblog = models.CharField(max_length=255, null=True, blank=True)
    video_blog = models.CharField(max_length=255, null=True, blank=True)
    seo_descripcion = models.CharField(max_length=165,null=True, blank=True)
    slug = models.SlugField(editable=False, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.titulo)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.titulo

blogapp/views.py
from django.shortcuts import render, get_list_or_404
from .models import Post

# Create your Views here.

def blog_list(request):
    post_list = Post.objects.order_by('creado').filter(estado='Publicado')
    context = {
        'post_list': post_list,
    }
    template = 'blogapp/blog_list.html'
    return render(request, template, context)


def blog_detail(request, slug):
    post = get_list_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    template = 'blogapp/blog_detail.html'
    return render(request,template,context)

templates/blogapp/blog_base.html
{% load thumbnail %}
{% load staticfiles %}
{% load static %}
<style>
.post-box-contenedor{
height: 390px;
padding: 14px;
border-radius: 12px;
border:1px solid #f4f2ed;
}
.date-feature {
background: #20202f none repeat scroll 0 0;
border-radius: 17px;
color: #ffffff;
font-family: "Quicksand", sans-serif;
font-size: 24px;
font-weight: 700;
height: 78px;
padding: 12px 5px;
position: absolute;
right: 20px;
text-align: center;
top: 20px;
width: 78px;
z-index: 1;
}
img {
max-width: 100%;
}
.post-thumb img {
border-radius: 12px;
}
.post-meta {
-webkit-box-align: center;
-ms-flex-align: center;
-ms-grid-row-align: center;
align-items: center;
-webkit-box-pack: justify;
-ms-flex-pack: justify;
justify-content: space-between;
}
.post-author a,
.post-date a,
.post-favourite a,
.post-comments a,
.post-share a {
color: #96989f;
font-size: 12px;
}
.post-author a:hover,
.post-date a:hover,
.post-favourite a:hover,
.post-comments a:hover,
.post-share a:hover {
color: #000;
}
.post-favourite a,
.post-comments a {
margin-right: 15px;
}
.post-author a {
margin-right: 15px;
position: relative;
z-index: 1;
}
.single-post {
margin-bottom: 30px;
}
.single-post h4 {
margin: 10px 0;
color: #000;
-webkit-transition-duration: 500ms;
transition-duration: 500ms;
font-size: 24px;
font-weight: 600;
}
.single-post p {
color: #96989f;
font-size: 12px;
}
/*--------------------------------  ENLACE TODOS LOS SHOWS ----*/
.enlace-blog-box{
text-align: center;
padding-top: 20px;
padding-bottom: 44px;
}
.enlace-blog-vertodo{
font-family: 'SF Pro Display';
display: inline-block;
font-size: 14px;
font-weight: 400;
font-style: normal;
color: #e4b760;
}
.enlace-blog-vertodo:hover{
font-family: 'SF Pro Display';
font-size: 14px;
font-weight: 400;
font-style: normal;
color: #54175e;
text-decoration: none;
}

.owl-theme .owl-nav .owl-prev {
background: url("../static/img/blogapp/arrow-left-active.png") no-repeat center center;
float: left;
height: 50px;
left: -90px;
width: 50px;
top: 40%;
-webkit-transform: translateY(-50%);
-moz-transform: translateY(-50%);
-ms-transform: translateY(-50%);
-o-transform: translateY(-50%);
transform: translateY(-50%);
text-indent: -10000px;
position: absolute;
}
.owl-theme .owl-nav .owl-prev:hover {
background: url("../static/img/blogapp/arrow-left-active.png") no-repeat center center;
}
.owl-theme .owl-nav .owl-next {
background: url("../static/img/blogapp/arrow-right-active.png") no-repeat center center;
float: left;
height: 50px;
right: -90px;
width: 50px;
top: 40%;
-webkit-transform: translateY(-50%);
-moz-transform: translateY(-50%);
-ms-transform: translateY(-50%);
-o-transform: translateY(-50%);
transform: translateY(-50%);
text-indent: -10000px;
position: absolute;
}
.owl-theme .owl-nav .owl-next:hover {
background: url("../static/img/blogapp/arrow-right-active.png") no-repeat center center;
}
.read-more {
font-family: 'SF Pro Display';
font-size: 10px;
font-weight: 600;
border: 2px solid #e8163f;
color: #fff;
border-radius: 6px;
width: 120px;
margin-right: auto;
margin-left: auto;
height: 32px;
text-align: center;
background: #e8163f;
line-height: 14px;
}
.box-noticia-titulo{
text-align: center;
vertical-align: middle;
margin: 0 auto;
justify-content: center;
padding-top: 22px;
padding-bottom: 18px;
}
.titulo-blog{
font-size: 20px;
color: #000000;
padding-top: 12px;
font-weight: 600;
}

.contenido-blog{
font-size: 10px;
}
/* ----------- iPhone 5, 5S, 5C and 5SE ----------- */
@media (min-width: 319px) and (max-width:373px) {
.post-box-contenedor{
height: 370px;
padding: 12px;
border-radius: 12px;
border:1px solid #f4f2ed;
}
.titulo-blog{
font-size: 18px;
color: #000000;
padding-top: 8px;
font-weight: 600;
}
.contenido-blog{
font-size: 10px;
}
/*--------------------------------  ENLACE TODOS LOS SHOWS ----*/
.enlace-blog-box{
text-align: center;
padding-top: 0px;
padding-bottom: 22px;
}
.enlace-blog-vertodo{
font-family: 'SF Pro Display';
display: inline-block;
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #96989f;
}
.enlace-blog-vertodo:hover{
font-family: 'SF Pro Display';
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #54175e;
text-decoration: none;
}
}
/* ----------- iPhone 6, 6S, 7 and 8 ----------- */
@media (min-width:374px) and (max-width: 412px){
.post-box-contenedor{
height: 364px;
padding: 12px;
border-radius: 12px;
border:1px solid #f4f2ed;
}
.titulo-blog{
font-size: 18px;
color: #000000;
padding-top: 8px;
font-weight: 600;
}
.contenido-blog{
font-size: 10px;
}
/*--------------------------------  ENLACE TODOS LOS SHOWS ----*/
.enlace-blog-box{
text-align: center;
padding-top: 0;
padding-bottom: 22px;
}
.enlace-blog-vertodo{
font-family: 'SF Pro Display';
display: inline-block;
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #96989f;
}
.enlace-blog-vertodo:hover{
font-family: 'SF Pro Display';
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #54175e;
text-decoration: none;
}
}
/* ----------- iPhone 6+, 7+ and 8+ ----------- */
@media (min-width: 413px) and (max-width: 767px){
    .post-box-contenedor{
height: 390px;
padding: 12px;
border-radius: 12px;
border:1px solid #f4f2ed;
}
.titulo-blog{
font-size: 20px;
color: #000000;
padding-top: 12px;
font-weight: 600;
}
.contenido-blog{
font-size: 12px;
}
/*--------------------------------  ENLACE TODOS LOS SHOWS ----*/
.enlace-blog-box{
text-align: center;
padding-top: 0px;
padding-bottom: 22px;
}
.enlace-blog-vertodo{
font-family: 'SF Pro Display';
display: inline-block;
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #96989f;
}
.enlace-blog-vertodo:hover{
font-family: 'SF Pro Display';
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #54175e;
text-decoration: none;
}
}
/* ----------- iPad 1, 2, Mini and Air ----------- */
/* ----------- iPad 3, 4 and Pro 9.7" ----------- */
@media (min-width: 768px) and (max-width: 992px){
.post-box-contenedor{
height: 390px;
padding: 12px;
border-radius: 12px;
border:1px solid #f4f2ed;
}
.titulo-blog{
font-size: 20px;
color: #000000;
padding-top: 12px;
font-weight: 600;
}
.contenido-blog{
font-size: 12px;
}
/*--------------------------------  ENLACE TODOS LOS SHOWS ----*/
.enlace-blog-box{
text-align: center;
padding-top: 0;
padding-bottom: 22px;
}
.enlace-blog-vertodo{
font-family: 'SF Pro Display';
display: inline-block;
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #96989f;
}
.enlace-blog-vertodo:hover{
font-family: 'SF Pro Display';
font-size: 12px;
font-weight: 400;
font-style: normal;
color: #54175e;
text-decoration: none;
}
}
</style>
{% block content %}
<div class="container-fluid box-blog" id="menu-blog">
    <div class="container">
    <div class="row">
            <div class="colmd-12 col-12 box-noticia-titulo">
                <img class="justify-content-center logo-murtado reveal-img-principal" src={% static 'img/logo/murtao-logo4.svg' %}>
                <h6 class="header-evento reveal-titulo">Blog & Noticias</h6>
                <h6 class="header-descripcion reveal-descripcion">recetas, promociones y novedades</h6>
            </div>
        </div>
        <div class="row">
            <div class="owl-carousel owl-theme reveal-textoleft" data-autoplay="true" data-speed="1800" data-autotime="5000">
                {% for obj in post_list %}
                    <!-- %{ for }% -->
                    <div class="item post-box-contenedor">
                        <div class="single-post wow fadeInUp" data-wow-delay="1s">
                            <div class="post-thumb">
                                <img src="{{ obj.imagen_blog|thumbnail_url:'blog' }}">
                            </div>
                            <div class="post-content">
                                <div class="post-meta d-flex">
                                    <div class="post-author-date-area d-flex">
                                        <div class="post-author">
                                            <a href="#"><i class="fa fa-calendar" aria-hidden="true"></i> {{ obj.fecha_blog|date:"d"}} de {{ obj.fecha_blog|date:"F"}}</a>
                                        </div>
                                        <div class="post-date">
                                            <a href="#"><i class="fa fa-clock-o" aria-hidden="true"></i> {{ obj.hora_blog }} {{ obj.hora_blog|date:"A" }}</a>
                                        </div>
                                    </div>
                                    <div class="post-comment-share-area d-flex">
                                        <div class="post-favourite">
                                            <a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i> 10</a>
                                        </div>
                                        <div class="post-comments">
                                            <a href="#"><i class="fa fa-comment-o" aria-hidden="true"></i> 12</a>
                                        </div>
                                        <div class="post-share">
                                            <a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <a href="{% url 'blogapp:blog_detail' slug=obj.slug %}">
                                    <h6 class="titulo-blog">{{ obj.titulo }}</h6>
                                </a>
                                <p class="contenido-blog">{{ obj.contenido|truncatechars:100 }}</p>
                                <div class="container-boton">
                                    <a href="{% url 'blogapp:blog_detail' slug=obj.slug %}" class="btn read-more">Continuar Leyendo <span class="fa fa-long-arrow-right fa-1x"></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12 enlace-blog-box">
                <a href="{% url 'blogapp:blog_list' %}" class="enlace-blog-vertodo"> <span class="fa fa-long-arrow-right fa-1x"></span></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<script>
$('.owl-carousel').each(function() {
var owl = $('.owl-carousel');
$(this).owlCarousel({
margin: 15,
loop: true,
autoplayTimeout: $(this).data('autotime'),
smartSpeed: $(this).data('speed'),
autoplay: $(this).data('autoplay'),
item: $(this).data('carousel-items'),
nav: false,
dots: $(this).data('dots'),
responsive:{
320: {
items: 1,
margin: 15
},
768: {
items: 2,
margin: 15
},
992: {
items: $(this).data('laptop')
},
1200: {
items: $(this).data('items')
}
}
});
});
</script>

templates/blogapp/blog_detail.html
{% block content %}
    {% for post in post %}
    <img width="" class="" src="{{ post.imagen_blog.url }}"/>
    <h1>{{ post.titulo }}</h1>
    <h1>{{ post.contenido }}</h1>
    <h1>{{ post.fecha_blog }}</h1>
    <h1>{{ post.hora_blog }}</h1>
    <h1>{{ post.linkblog }}</h1>
    <h1>{{ post.video_blog }}</h1>
    {% endfor %}
{% endblock %}

templates/blogapp/blog_list.html
{% block content %}

            <section class="blog_area ">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="row">

                        {% for obj in post_list %}
                        <div class="col-4">
                            <div class="single-post wow fadeInUp" data-wow-delay="1s">
                                <!-- Post Thumb -->
                                <div class="post-thumb">
                                    <img src="{{ obj.imagen_blog.url }}" alt="">
                                </div>
                                <!-- Post Content -->
                                <div class="post-content">
                                    <div class="post-meta d-flex">
                                        <div class="post-author-date-area d-flex">
                                            <!-- Post Author -->
                                            <div class="post-author">
                                                <a href="#">{{ obj.fecha_blog }}</a>
                                            </div>
                                            <!-- Post Date -->
                                            <div class="post-date">
                                                <a href="#">{{ obj.hora_blog }}</a>
                                            </div>
                                        </div>
                                        <!-- Post Comment & Share Area -->
                                        <div class="post-comment-share-area d-flex">
                                            <!-- Post Favourite -->
                                            <div class="post-favourite">
                                                <a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i> 10</a>
                                            </div>
                                            <!-- Post Comments -->
                                            <div class="post-comments">
                                                <a href="#"><i class="fa fa-comment-o" aria-hidden="true"></i> 12</a>
                                            </div>
                                            <!-- Post Share -->
                                            <div class="post-share">
                                                <a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="{% url 'blogapp:blog_detail' slug=obj.slug %}">
                                        <h4 class="post-headline">{{ obj.titulo }}</h4>
                                    </a>
                                    <p>{{ obj.contenido|truncatechars:160 }}</p>
                                    <a href="{% url 'blogapp:blog_detail' slug=obj.slug %}" class="read-more">Continuar Leyendo</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>

        </section>

{% endblock %}

templates/blogapp/blog_respaldo.html
<h6><a href="{% url 'menuapp:menu_category' slug=obj.categoria.slug %}">{{ obj.categoria }}</a></h6>




    {% load staticfiles %}
    {% load static %}

               <div class="container">
                <div class="card gedf-card">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">

                            <li class="nav-item">
                                <a class="nav-link active" id="posts-tab"  href="#posts" role="tab" aria-controls="posts" aria-selected="true" data-toggle="tab" >Make a publication</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="caca-tab" data-toggle="tab" role="tab" aria-controls="caca" aria-selected="false" href="#caca">Hola</a>
                            </li>

                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content" id="myTabContent">

                            <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                                <div class="form-group">
                                    <label class="sr-only" for="message">post</label>
                                    <textarea class="form-control" id="message" rows="3" placeholder="What are you thinking?"></textarea>
                                </div>
                            </div>

                            <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                                <div class="form-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="customFile">
                                        <label class="custom-file-label" for="customFile">Upload image</label>
                                    </div>
                                </div>
                                <div class="py-4"></div>
                            </div>

                            <div class="tab-pane fade" id="caca" role="tabpanel" aria-labelledby="caca-tab">
                                <div class="form-group">
                                    <div class="row ">
                                        {% include 'menuapp/menu_categorias/almuerzos.html' %}
                                    </div>
                                </div>
                            </div>

                        <div class="btn-toolbar justify-content-between">
                            <div class="btn-group">
                                <button type="submit" class="btn btn-primary">share</button>
                            </div>

                            <div class="btn-group">
                                <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="fa fa-globe"></i> Public
                                </button>
                                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                    <a class="dropdown-item" href="#"><i class="fa fa-globe"></i> Public</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-users"></i> Friends</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Just me</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               </div>

               <div class="container">
                <h1>Portfolio Gallery Filter</h1><br>
                <div class="row">


                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">

                  <li class="nav-item">
                    <a class="nav-link active" id="showall-tab" data-toggle="pill" href="#showall" role="tab" aria-controls="showall" aria-selected="true">Show All</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="Cars-tab" data-toggle="pill" href="#Cars" role="tab" aria-controls="Cars" aria-selected="false">Cars</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="City-tab" data-toggle="pill" href="#City" role="tab" aria-controls="City" aria-selected="false">City</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="Forest-tab" data-toggle="pill" href="#Forest" role="tab" aria-controls="Forest" aria-selected="false">Forest</a>
                  </li>

                </ul>

                </div>
                <div class="container">
                <div class="tab-content" id="pills-tabContent">
                  <div class="tab-pane fade show active" id="showall" role="tabpanel" aria-labelledby="showall-tab">
                      <div class="row">
                          <div class="col-12">
                              <div class="row">
                                  <div class="col-4">
                                        <div class="Portfolio"><a href="#!"><img class="card-img" src="{% static 'img/logo/murtao-logo3.svg' %}" alt=""></a><div class="desc">Car 1</div></div>
                                  </div>
                                    <div class="col-4">
                                        <div class="Portfolio"><a href="#!"><img class="card-img" src="{% static 'img/logo/murtao-logo3.svg' %}" alt=""></a><div class="desc">City 1</div></div>
                                    </div>
                                    <div class="col-4">
                                        <div class="Portfolio"><a href="#!"><img class="card-img" src="{% static 'img/logo/murtao-logo3.svg' %}" alt=""></a><div class="desc">Car 2</div></div>
                                  </div>
                              </div>
                          </div>

                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Forest 1</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Forest 2</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">City 2</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Car 3</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">City 3</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Forest 3</div></div>
                          </div>

                  </div>
                  <div class="tab-pane fade" id="Cars" role="tabpanel" aria-labelledby="Cars-tab">
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Car 1</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Car 2</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Car 3</div></div>
                  </div>
                  <div class="tab-pane fade" id="City" role="tabpanel" aria-labelledby="City-tab">
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">City 1</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">City 2</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">City 3</div></div>
                  </div>
                  <div class="tab-pane fade" id="Forest" role="tabpanel" aria-labelledby="Forest-tab">
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Forest 1</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Forest 2</div></div>
                    <div class="Portfolio"><a href="#!"><img class="card-img" src="http://placehold.it/400x400" alt=""></a><div class="desc">Forest 3</div></div>
                  </div>
                </div>
                </div>
               </div>
                </div>

    <section class="container mt-4 mb-4">

        <div class="row ">
            <div class="col-md-4">
                <div class="d-flex flex-row border rounded">
                    <div class="p-1 ">
                        <img src="{% static 'img/menuapp/1.jpg' %}" class="rounded-circle border-0" />
                    </div>
                    <div class="pl-3 pt-2 pr-2 pb-2 w-75 border-left">
                            <h6 class="">Leanne Boulton</h6>
                            <p style="font-size: 10px; color: gray" class="">Tiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
                    </div>
                    <div class="">
                        <span class="badge badge-warning text-right mb-5">$9.000</span>
                        <div class="pt-5">
                            <img class="d-flex pt-5" src="{% static 'img/logo/murtao-logo.svg' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="d-flex flex-row border rounded">
                    <div class="p-1 ">
                        <img src="{% static 'img/menuapp/2.jpg' %}" class="rounded-circle border-0" />
                    </div>
                    <div class="pl-3 pt-2 pr-2 pb-2 w-75 border-left">
                            <h6 class="">Leanne Boulton</h6>
                            <p style="font-size: 10px; color: gray" class="">Tiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
                    </div>
                    <div class="">
                        <span class="badge badge-warning text-right mb-5">$9.000</span>
                        <div class="pt-5">
                            <img class="d-flex pt-5" src="{% static 'img/logo/murtao-logo.svg' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="d-flex flex-row border rounded">
                    <div class="p-1 ">
                        <img src="{% static 'img/menuapp/3.jpg' %}" class="rounded-circle border-0" />
                    </div>
                    <div class="pl-3 pt-2 pr-2 pb-2 w-75 border-left">
                            <h6 class="">Leanne Boulton</h6>
                            <p style="font-size: 10px; color: gray" class="">Tiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
                    </div>
                    <div class="">
                        <span class="badge badge-warning text-right mb-5">$9.000</span>
                        <div class="pt-5">
                            <img class="d-flex pt-5" src="{% static 'img/logo/murtao-logo.svg' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>