blogapp/urls.py
from django.urls import path
from .views import blog_detail, blog_list


urlpatterns = [
    path('', blog_list, name="blog_list"),
    path('<slug:slug>/', blog_detail, name='blog_detail'),
]

control_panelapp/urls.py
from django.urls import path

from suscripcionapp.views import control_suscripcion, control_suscripcion_lista, control_suscripcion_detalle, \
    control_suscripcion_editar, control_suscripcion_eliminar


urlpatterns = [
    path('suscripcion/', control_suscripcion, name="control_suscripcion"),
    path('suscripcion-lista/', control_suscripcion_lista, name="control_suscripcion_lista"),
    path('suscripcion-detalle/<int:pk>/', control_suscripcion_detalle, name="control_suscripcion_detalle"),
    path('suscripcion-editar/<int:pk>/', control_suscripcion_editar, name="control_suscripcion_editar"),
    path('suscripcion-eliminar/<int:pk>/', control_suscripcion_eliminar, name="control_suscripcion_eliminar"),

]

murtaoweb/urls.py
from django.contrib import admin
from django.urls import path
from murtaoweb import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include(('blogapp.urls', 'blogapp'), namespace='blogapp')),
    path('eventos/', include(('eventosapp.urls', 'eventosapp'), namespace='eventosapp')),
    path('menu/', include(('menuapp.urls', 'menuapp'), namespace='menuapp')),
    path('contacto/', include(('contacto.urls', 'contacto'), namespace='contacto')),
    path('carta/', include(('cartaapp.urls', 'carta'), namespace='carta')),

    path('control/', include(('control_panelapp.urls', 'control_panelapp'), namespace='control_panelapp')),
    path('reservas/', include(('reservasapp.urls', 'reservasapp'), namespace='reservasapp')),
    path('suscripcion/', include(('suscripcionapp.urls', 'suscripcionapp'), namespace='suscripcionapp')),
    path('enviando/', TemplateView.as_view(template_name="reservasapp/contacto_enviando.html")),
    path('redirect/', TemplateView.as_view(template_name="reservasapp/reserva_redirect.html"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

control_panelapp/models.py
from django.db import models

# Create your models here.

control_panelapp/views.py
from django.shortcuts import render

# Create your views here.

templates/control_panelapp/control_suscripcion.html
{% extends "control_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1 class="page-header">Dashboard</h1>
    <form method="POST">{%  csrf_token %}
    {{ form|crispy }}
        <button class="btn btn-default"  type="submit">Save</button>
    </form>
                 <div class="col-sm-2">
                 <a href="{% url "control_panelapp:control_suscripcion_lista" %}">
                     <button type="button" class="btn btn-success">Lista Suscripcion</button></a>
             </div>

{% endblock %}

templates/control_panelapp/control_suscripcion_detalle.html
{% extends "control_base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header">
            <h1>{{ suscripcion.subject }}</h1>
            <p>{{ suscripcion.body }}</p>
            <p>{{ suscripcion.fecha_evento }}</p>

        </div>
    {{ newsletter.body }}
    <div class="col-sm-8 col-sm-offset-4">
        <div class="col-sm-2"><a href="{% url 'control_panelapp:control_suscripcion_editar' pk=suscripcion.pk %}"><button class="btn btn-info">Edit</button></a></div>
        <div class="col-sm-2"><a href="{% url "control_panelapp:control_suscripcion_eliminar" pk=suscripcion.pk %}"><button class="btn btn-danger">Delete</button></a></div>
        <div class="col-sm-2"><a href="{% url 'control_panelapp:control_suscripcion' %}"><button class="btn btn-success">New</button></a></div>
        </div>
    </div>

{% endblock %}

templates/control_panelapp/control_suscripcion_eliminar.html
{% extends "control_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1 class="page-header">Dashboard</h1>
    <form method="POST">{%  csrf_token %}
    {{ form|crispy }}
        <button class="btn btn-danger"  type="submit">Delete</button>
    </form>
                 <div class="col-sm-2">
                 <a href="{% url "control_panelapp:control_suscripcion_lista" %}">
                     <button type="button" class="btn btn-success">Lista Suscripcion</button></a>
             </div>

{% endblock %}

templates/control_panelapp/control_suscripcion_lista.html
{% extends "control_base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

        <div class="row">
            <div class="col-sm-10">

                <h1 class="page-header">Toda las Suscripciones  </h1>


            </div>
             <div class="col-sm-2">
                 <a href="{% url "control_panelapp:control_suscripcion" %}">
                     <button type="button" class="btn btn-success">Nueva Suscripcipon</button></a>
             </div>
        </div>
        <div class="table-responsive table-hover">
            <table class="table">
                <thead>
                    <th>Suscripcion</th>
                    <th>Status</th>
                    <th>Created</th>
                    <th>Updated</th>
                <th>Edit</th>
                <th>Delete</th>
                </thead>
                <tbody>
                {% for item in items %}
                    <tr>
                        <td><a href="{% url "control_panelapp:control_suscripcion_detalle" pk=item.pk %}"> {{ item.subject }} ({{ item.subject|length }})</a></td>
                        <td>{{ item.status }}</td>
                        <td>{{ item.create }}</td>
                        <td>{{ item.update }}</td>

                        <td><a href="{% url "control_panelapp:control_suscripcion_editar" pk=item.pk %}">Edit</a></td>
                        <td><a href="{% url "control_panelapp:control_suscripcion_eliminar" pk=item.pk %}">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}